PN-10105: standardizzazione parametri cpu e mem
pagopa/pn-ec pull request #462
Opened 2024-03-20 17:56 UTC by Sibboard

2024-03-20 17:59 UTC, mottone-dgs approved these changes

2024-03-21 08:33 UTC, FeliceMente submitted a review, later dismissed

2024-03-21 08:39 UTC, FeliceMente commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "CpuValue": "4096",
per l'ambiente DEV vanno impostati questi parametri:
1024.0 vCPU/4096 MB memory

2024-03-21 10:22 UTC, Sibboard commented
aggiornati i parametri per dev ed eliminato il vecchio file di configurazione

2024-03-21 10:45 UTC, FeliceMente requested changes

2024-03-21 10:45 UTC, FeliceMente commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "CpuValue": "1024",
per l'ambiente DEV vanno impostati questi parametri:
1024.0 vCPU/4096 MB memory

2024-03-21 11:03 UTC, mottone-dgs commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "CpuValue": "1024",
fatto

2024-03-21 11:03 UTC, mottone-dgs submitted a review, later dismissed

2024-03-21 14:21 UTC, mottone-dgs submitted a review, later dismissed

2024-03-22 09:16 UTC, FeliceMente approved these changes

2024-03-22 09:17 UTC, merged