Feature/785
pagopa/pn-ec pull request #509
Opened 2024-07-26 09:58 UTC by NicoPonziani

Creazione variabili ambiente per Feature Flag e per il tipo documento utile per la comparazione

2024-07-29 15:56 UTC, DamianoLozzi commented on scripts/aws/cfn/microservice.yml
Test

2024-07-29 15:57 UTC, DamianoLozzi commented on scripts/aws/cfn/microservice.yml
>  Conditions:
test

2024-07-29 15:58 UTC, DamianoLozzi commented on scripts/aws/cfn/microservice.yml
>          ContainerEnvEntry68: !Sub 'PnEcNamirialServerCacheEndpoint=${PnEcNamirialServerCacheEndpoint}'
test

2024-07-29 15:59 UTC, DamianoLozzi commented on scripts/aws/cfn/microservice.yml
> +    Type: String
test review

2024-07-29 16:00 UTC, mottone-dgs requested changes

2024-07-29 16:00 UTC, mottone-dgs commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "PdfRasterDocumentTypeToConvert": "PN_NOTIFICATION_ATTACHMENT"
il tipo corretto è PN_NOTIFICATION_ATTACHMENTS

2024-07-29 16:00 UTC, mottone-dgs commented on scripts/aws/cfn/microservice.yml
> +        ContainerEnvEntry73: !Sub 'PdfRasterDocumentTypeToConvert=${PdfRasterDocumentTypeToConvert}'
attenzione a non lasciare buchi nella numerazione

2024-08-01 09:16 UTC, mottone-dgs approved these changes

2024-08-01 09:16 UTC, merged